# just wait for PR to run on main as a tirgger
pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2
  pipelines:
    - pipeline: pr
      source: PR
      trigger:
        branches:
          include:
            - main

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 0
    skipAzureAuth: true
    globalVariables:
      - template: .azure/pipelines/variables.yml@self
    validationJobs:
      - name: Function Build
        steps:
          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)" | package-lock.json
              path: $(npm_config_cache)
            displayName: Cache NPM
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm ci --omit=dev --workspace=appeals-migration-function --workspace=@pins/appeals-migration-database --workspace=@pins/appeals-migration-lib --workspace=@pins/manage-appeals-database
              workingDirectory: $(Build.Repository.LocalPath)
              environmentVariables:
                npm_config_cache: $(npm_config_cache)
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run db-generate
              workingDirectory: $(Build.Repository.LocalPath)
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              # generate @pins/manage-appeals-database client
              script: npm run fetch-schema --workspace=@pins/manage-appeals-database && npm run generate --workspace=@pins/manage-appeals-database
          - script: |
              source ~/.bashrc
              # copy root node_modules to function (but don't overwrite)
              rsync -a -r --ignore-existing $(Build.Repository.LocalPath)/node_modules/ $(Build.Repository.LocalPath)/apps/function/node_modules/
              # ensure there is a @pins/appeals-migration-database folder
              mkdir -p $(Build.Repository.LocalPath)/apps/function/src/packages/appeals-migration-database
              # ensure there is a @pins/manage-appeals-database folder
              mkdir -p $(Build.Repository.LocalPath)/apps/function/src/packages/manage-appeals-database
              # ensure there is a @pins/appeals-migration-lib folder
              mkdir -p $(Build.Repository.LocalPath)/apps/function/src/packages/appeals-migration-lib
              # copy db package to packages/appeals-migration-database folder
              cp -r $(Build.Repository.LocalPath)/packages/database/* $(Build.Repository.LocalPath)/apps/function/src/packages/appeals-migration-database/
              # copy db package to packages/manage-appeals-database folder
              cp -r $(Build.Repository.LocalPath)/packages/database-sink/* $(Build.Repository.LocalPath)/apps/function/src/packages/manage-appeals-database/
              # copy lib package to packages/appeals-migration-lib folder
              cp -r $(Build.Repository.LocalPath)/packages/lib/* $(Build.Repository.LocalPath)/apps/function/src/packages/appeals-migration-lib/
              # remove the package files to avoid subpath import issues - treat them as part of the functions code src
              rm $(Build.Repository.LocalPath)/apps/function/src/packages/appeals-migration-database/package.json
              rm $(Build.Repository.LocalPath)/apps/function/src/packages/manage-appeals-database/package.json
              rm $(Build.Repository.LocalPath)/apps/function/src/packages/appeals-migration-lib/package.json
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              # we do this after the above copy step so that the replacements can also apply to the packages themselves
              script: npm run prepare-package
              workingDirectory: $(Build.Repository.LocalPath)/apps/function
          - task: ArchiveFiles@2
            displayName: Archive files
            inputs:
              rootFolderOrFile: $(Build.Repository.LocalPath)/apps/function
              includeRootFolder: false
              archiveFile: $(System.DefaultWorkingDirectory)/functions.zip
          - publish: $(System.DefaultWorkingDirectory)/functions.zip
            artifact: functions
            displayName: Publish Functions Artifact
