parameters:
  - name: schemaMigration
    displayName: Run SQL Database Migration
    type: boolean
    default: true

pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2
  pipelines:
    - pipeline: build
      source: Build
      trigger:
        branches:
          include:
            - main

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    variableGroupPrefix: 'cd'
    environments:
      - name: Test
      - name: Prod
        dependsOn:
          - Test
    globalVariables:
      - template: .azure/pipelines/variables.yml@self
    deploymentStages:
      - name: Deploy
        deploymentJobs:
          - name: Migrate
            condition: ${{ eq(parameters.schemaMigration, true) }}
            steps:
              - checkout: self
              - template: ../steps/azure_get_secrets.yml@templates
                parameters:
                  keyVaultName: pins-kv-appeals-migration-$(ENVIRONMENT)
                  secrets:
                    - name: appeals-migration-sql-admin-connection-string
                      variable: SQL_CONNECTION_STRING_ADMIN
                    - name: appeals-migration-sql-app-connection-string
                      variable: SQL_CONNECTION_STRING
              - template: ../steps/node_script.yml@templates
                parameters:
                  nodeVersion: 22
                  script: npm ci --workspace=@pins/appeals-migration-database
                  workingDirectory: $(Build.Repository.LocalPath)
              - ${{ if eq(parameters.schemaMigration, true) }}:
                  - template: ../steps/node_script.yml@templates
                    parameters:
                      nodeVersion: 22
                      environmentVariables:
                        SQL_CONNECTION_STRING_ADMIN: $(SQL_CONNECTION_STRING_ADMIN)
                      script: npm run migrate-prod
                      workingDirectory: $(Build.Repository.LocalPath)/packages/database
          - name: Deploy Functions
            steps:
              - download: build
                artifact: functions
                displayName: Download functions
              - template: ../steps/function_app_deploy.yml
                parameters:
                  appName: pins-func-appeals-migration-integration-$(ENVIRONMENT)
                  resourceGroup: $(resourceGroup)
                  workingDirectory: $(Pipeline.Workspace)/build/functions
