import { APPEAL_CASE_STAGE, APPEAL_DOCUMENT_TYPE } from '@planning-inspectorate/data-model';

const APPELLANT_CASE_DOCUMENT_TYPES = [
	APPEAL_DOCUMENT_TYPE.APPELLANT_STATEMENT,
	APPEAL_DOCUMENT_TYPE.ORIGINAL_APPLICATION_FORM,
	APPEAL_DOCUMENT_TYPE.APPLICATION_DECISION_LETTER,
	APPEAL_DOCUMENT_TYPE.CHANGED_DESCRIPTION,
	APPEAL_DOCUMENT_TYPE.APPELLANT_CASE_WITHDRAWAL_LETTER,
	APPEAL_DOCUMENT_TYPE.APPELLANT_CASE_CORRESPONDENCE,
	APPEAL_DOCUMENT_TYPE.DESIGN_ACCESS_STATEMENT,
	APPEAL_DOCUMENT_TYPE.PLANS_DRAWINGS,
	APPEAL_DOCUMENT_TYPE.NEW_PLANS_DRAWINGS,
	APPEAL_DOCUMENT_TYPE.PLANNING_OBLIGATION,
	APPEAL_DOCUMENT_TYPE.OWNERSHIP_CERTIFICATE,
	APPEAL_DOCUMENT_TYPE.OTHER_NEW_DOCUMENTS,
	APPEAL_DOCUMENT_TYPE.ENVIRONMENTAL_ASSESSMENT,
	APPEAL_DOCUMENT_TYPE.STATEMENT_COMMON_GROUND,
	APPEAL_DOCUMENT_TYPE.PRIOR_CORRESPONDENCE_WITH_PINS,
	APPEAL_DOCUMENT_TYPE.ENFORCEMENT_NOTICE,
	APPEAL_DOCUMENT_TYPE.ENFORCEMENT_NOTICE_PLAN,
	APPEAL_DOCUMENT_TYPE.GROUND_A_SUPPORTING,
	APPEAL_DOCUMENT_TYPE.GROUND_B_SUPPORTING,
	APPEAL_DOCUMENT_TYPE.GROUND_C_SUPPORTING,
	APPEAL_DOCUMENT_TYPE.GROUND_D_SUPPORTING,
	APPEAL_DOCUMENT_TYPE.GROUND_E_SUPPORTING,
	APPEAL_DOCUMENT_TYPE.GROUND_F_SUPPORTING,
	APPEAL_DOCUMENT_TYPE.GROUND_G_SUPPORTING,
	APPEAL_DOCUMENT_TYPE.GROUND_A_FEE_RECEIPT
];

const LPA_QUESTIONNAIRE_DOCUMENT_TYPES = [
	APPEAL_DOCUMENT_TYPE.WHO_NOTIFIED,
	APPEAL_DOCUMENT_TYPE.WHO_NOTIFIED_SITE_NOTICE,
	APPEAL_DOCUMENT_TYPE.WHO_NOTIFIED_LETTER_TO_NEIGHBOURS,
	APPEAL_DOCUMENT_TYPE.WHO_NOTIFIED_PRESS_ADVERT,
	APPEAL_DOCUMENT_TYPE.CONSERVATION_MAP,
	APPEAL_DOCUMENT_TYPE.OTHER_PARTY_REPRESENTATIONS,
	APPEAL_DOCUMENT_TYPE.PLANNING_OFFICER_REPORT,
	APPEAL_DOCUMENT_TYPE.PLANS_DRAWINGS,
	APPEAL_DOCUMENT_TYPE.DEVELOPMENT_PLAN_POLICIES,
	APPEAL_DOCUMENT_TYPE.TREE_PRESERVATION_PLAN,
	APPEAL_DOCUMENT_TYPE.DEFINITIVE_MAP_STATEMENT,
	APPEAL_DOCUMENT_TYPE.COMMUNITY_INFRASTRUCTURE_LEVY,
	APPEAL_DOCUMENT_TYPE.SUPPLEMENTARY_PLANNING,
	APPEAL_DOCUMENT_TYPE.EMERGING_PLAN,
	APPEAL_DOCUMENT_TYPE.CONSULTATION_RESPONSES,
	APPEAL_DOCUMENT_TYPE.EIA_ENVIRONMENTAL_STATEMENT,
	APPEAL_DOCUMENT_TYPE.EIA_SCREENING_OPINION,
	APPEAL_DOCUMENT_TYPE.EIA_SCOPING_OPINION,
	APPEAL_DOCUMENT_TYPE.EIA_SCREENING_DIRECTION,
	APPEAL_DOCUMENT_TYPE.LPA_CASE_CORRESPONDENCE,
	APPEAL_DOCUMENT_TYPE.OTHER_RELEVANT_POLICIES,
	APPEAL_DOCUMENT_TYPE.APPEAL_NOTIFICATION,
	APPEAL_DOCUMENT_TYPE.HISTORIC_ENGLAND_CONSULTATION,
	APPEAL_DOCUMENT_TYPE.RELATED_APPLICATIONS,
	APPEAL_DOCUMENT_TYPE.STOP_NOTICE,
	APPEAL_DOCUMENT_TYPE.ARTICLE_4_DIRECTION,
	APPEAL_DOCUMENT_TYPE.ENFORCEMENT_LIST,
	APPEAL_DOCUMENT_TYPE.LOCAL_DEVELOPMENT_ORDER,
	APPEAL_DOCUMENT_TYPE.PLANNING_PERMISSION,
	APPEAL_DOCUMENT_TYPE.LPA_ENFORCEMENT_NOTICE,
	APPEAL_DOCUMENT_TYPE.LPA_ENFORCEMENT_NOTICE_PLAN,
	APPEAL_DOCUMENT_TYPE.PLANNING_CONTRAVENTION_NOTICE
];

const COSTS_DOCUMENT_TYPES = [
	APPEAL_DOCUMENT_TYPE.APPELLANT_COSTS_APPLICATION,
	APPEAL_DOCUMENT_TYPE.APPELLANT_COSTS_WITHDRAWAL,
	APPEAL_DOCUMENT_TYPE.APPELLANT_COSTS_CORRESPONDENCE,
	APPEAL_DOCUMENT_TYPE.LPA_COSTS_APPLICATION,
	APPEAL_DOCUMENT_TYPE.LPA_COSTS_WITHDRAWAL,
	APPEAL_DOCUMENT_TYPE.LPA_COSTS_CORRESPONDENCE,
	APPEAL_DOCUMENT_TYPE.APPELLANT_COSTS_DECISION_LETTER,
	APPEAL_DOCUMENT_TYPE.LPA_COSTS_DECISION_LETTER
];

const INTERNAL_DOCUMENT_TYPES = [
	APPEAL_DOCUMENT_TYPE.CROSS_TEAM_CORRESPONDENCE,
	APPEAL_DOCUMENT_TYPE.INSPECTOR_CORRESPONDENCE,
	APPEAL_DOCUMENT_TYPE.MAIN_PARTY_CORRESPONDENCE,
	APPEAL_DOCUMENT_TYPE.UNCATEGORISED
];

const APPEAL_DECISION_DOCUMENT_TYPES = [APPEAL_DOCUMENT_TYPE.CASE_DECISION_LETTER];

export const FOLDERS: string[] = [
	...APPELLANT_CASE_DOCUMENT_TYPES.map((docType) => `${APPEAL_CASE_STAGE.APPELLANT_CASE}/${docType}`),
	...LPA_QUESTIONNAIRE_DOCUMENT_TYPES.map((docType) => `${APPEAL_CASE_STAGE.LPA_QUESTIONNAIRE}/${docType}`),
	...COSTS_DOCUMENT_TYPES.map((docType) => `${APPEAL_CASE_STAGE.COSTS}/${docType}`),
	...INTERNAL_DOCUMENT_TYPES.map((docType) => `${APPEAL_CASE_STAGE.INTERNAL}/${docType}`),
	...APPEAL_DECISION_DOCUMENT_TYPES.map((docType) => `${APPEAL_CASE_STAGE.APPEAL_DECISION}/${docType}`),
	'representation/representationAttachments'
];
