BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[appeal_document] (
    [documentId] NVARCHAR(1000) NOT NULL,
    [caseId] INT,
    [caseReference] NVARCHAR(max),
    [version] INT,
    [filename] NVARCHAR(max),
    [originalFilename] NVARCHAR(max),
    [size] INT,
    [mime] NVARCHAR(max),
    [documentURI] NVARCHAR(max),
    [publishedDocumentURI] NVARCHAR(max),
    [virusCheckStatus] NVARCHAR(max),
    [fileMD5] NVARCHAR(max),
    [dateCreated] NVARCHAR(max),
    [dateReceived] NVARCHAR(max),
    [datePublished] NVARCHAR(max),
    [lastModified] NVARCHAR(max),
    [caseType] NVARCHAR(max),
    [redactedStatus] NVARCHAR(max),
    [documentType] NVARCHAR(max),
    [sourceSystem] NVARCHAR(max),
    [origin] NVARCHAR(max),
    [owner] NVARCHAR(max),
    [author] NVARCHAR(max),
    [description] NVARCHAR(max),
    [caseStage] NVARCHAR(max),
    [horizonFolderId] NVARCHAR(max),
    CONSTRAINT [appeal_document_pkey] PRIMARY KEY CLUSTERED ([documentId])
);

-- CreateTable
CREATE TABLE [dbo].[appeal_event] (
    [eventId] NVARCHAR(1000) NOT NULL,
    [caseReference] NVARCHAR(max),
    [eventType] NVARCHAR(max),
    [eventName] NVARCHAR(max),
    [eventStatus] NVARCHAR(max),
    [isUrgent] BIT,
    [eventPublished] BIT,
    [eventStartDateTime] NVARCHAR(max),
    [eventEndDateTime] NVARCHAR(max),
    [notificationOfSiteVisit] NVARCHAR(max),
    [addressLine1] NVARCHAR(max),
    [addressLine2] NVARCHAR(max),
    [addressTown] NVARCHAR(max),
    [addressCounty] NVARCHAR(max),
    [addressPostcode] NVARCHAR(max),
    CONSTRAINT [appeal_event_pkey] PRIMARY KEY CLUSTERED ([eventId])
);

-- CreateTable
CREATE TABLE [dbo].[appeal_event_estimate] (
    [id] INT NOT NULL,
    [caseReference] NVARCHAR(max),
    [preparationTime] DECIMAL(32,16),
    [sittingTime] DECIMAL(32,16),
    [reportingTime] DECIMAL(32,16),
    CONSTRAINT [appeal_event_estimate_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[appeal_folder] (
    [id] INT NOT NULL,
    [caseReference] NVARCHAR(max),
    [displayNameEnglish] NVARCHAR(max),
    [displayNameWelsh] NVARCHAR(max),
    [parentFolderId] INT,
    [caseStage] NVARCHAR(max),
    CONSTRAINT [appeal_folder_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[appeal_has] (
    [caseId] INT NOT NULL,
    [caseReference] NVARCHAR(max),
    [submissionId] NVARCHAR(max),
    [caseStatus] NVARCHAR(max),
    [caseType] NVARCHAR(max),
    [caseProcedure] NVARCHAR(max),
    [lpaCode] NVARCHAR(max),
    [caseOfficerId] NVARCHAR(max),
    [inspectorId] NVARCHAR(max),
    [allocationLevel] NVARCHAR(max),
    [allocationBand] DECIMAL(32,16),
    [caseSpecialisms] NVARCHAR(max),
    [caseSubmittedDate] NVARCHAR(max),
    [caseCreatedDate] NVARCHAR(max),
    [caseUpdatedDate] NVARCHAR(max),
    [caseValidDate] NVARCHAR(max),
    [caseValidationDate] NVARCHAR(max),
    [caseValidationOutcome] NVARCHAR(max),
    [caseValidationInvalidDetails] NVARCHAR(max),
    [caseValidationIncompleteDetails] NVARCHAR(max),
    [caseExtensionDate] NVARCHAR(max),
    [caseStartedDate] NVARCHAR(max),
    [casePublishedDate] NVARCHAR(max),
    [linkedCaseStatus] NVARCHAR(max),
    [leadCaseReference] NVARCHAR(max),
    [lpaQuestionnaireDueDate] NVARCHAR(max),
    [lpaQuestionnaireSubmittedDate] NVARCHAR(max),
    [lpaQuestionnaireCreatedDate] NVARCHAR(max),
    [lpaQuestionnairePublishedDate] NVARCHAR(max),
    [lpaQuestionnaireValidationOutcome] NVARCHAR(max),
    [lpaQuestionnaireValidationOutcomeDate] NVARCHAR(max),
    [lpaQuestionnaireValidationDetails] NVARCHAR(max),
    [lpaStatement] NVARCHAR(max),
    [caseWithdrawnDate] NVARCHAR(max),
    [caseTransferredDate] NVARCHAR(max),
    [transferredCaseClosedDate] NVARCHAR(max),
    [caseDecisionOutcomeDate] NVARCHAR(max),
    [caseDecisionPublishedDate] NVARCHAR(max),
    [caseDecisionOutcome] NVARCHAR(max),
    [caseCompletedDate] NVARCHAR(max),
    [enforcementNotice] BIT,
    [applicationReference] NVARCHAR(max),
    [applicationDate] NVARCHAR(max),
    [applicationDecision] NVARCHAR(max),
    [applicationDecisionDate] NVARCHAR(max),
    [caseSubmissionDueDate] NVARCHAR(max),
    [siteAddressLine1] NVARCHAR(max),
    [siteAddressLine2] NVARCHAR(max),
    [siteAddressTown] NVARCHAR(max),
    [siteAddressCounty] NVARCHAR(max),
    [siteAddressPostcode] NVARCHAR(max),
    [siteAccessDetails] NVARCHAR(max),
    [siteSafetyDetails] NVARCHAR(max),
    [siteAreaSquareMetres] DECIMAL(32,16),
    [floorSpaceSquareMetres] DECIMAL(32,16),
    [isCorrectAppealType] BIT,
    [isGreenBelt] BIT,
    [inConservationArea] BIT,
    [ownsAllLand] BIT,
    [ownsSomeLand] BIT,
    [knowsOtherOwners] NVARCHAR(max),
    [knowsAllOwners] NVARCHAR(max),
    [advertisedAppeal] BIT,
    [notificationMethod] NVARCHAR(max),
    [ownersInformed] BIT,
    [originalDevelopmentDescription] NVARCHAR(max),
    [changedDevelopmentDescription] BIT,
    [newConditionDetails] NVARCHAR(max),
    [nearbyCaseReferences] NVARCHAR(max),
    [neighbouringSiteAddresses] NVARCHAR(max),
    [reasonForNeighbourVisits] NVARCHAR(max),
    [affectedListedBuildingNumbers] NVARCHAR(max),
    [appellantCostsAppliedFor] BIT,
    [lpaCostsAppliedFor] BIT,
    [typeOfPlanningApplication] NVARCHAR(max),
    [affectsScheduledMonument] BIT,
    [hasProtectedSpecies] BIT,
    [isAonbNationalLandscape] BIT,
    [hasInfrastructureLevy] BIT,
    [isInfrastructureLevyFormallyAdopted] BIT,
    [infrastructureLevyAdoptedDate] NVARCHAR(max),
    [infrastructureLevyExpectedDate] NVARCHAR(max),
    [caseworkReason] NVARCHAR(max),
    [importantInformation] NVARCHAR(max),
    [jurisdiction] NVARCHAR(max),
    [redeterminedIndicator] BIT,
    [dateCostsReportDespatched] NVARCHAR(max),
    [dateNotRecoveredOrDerecovered] NVARCHAR(max),
    [dateRecovered] NVARCHAR(max),
    [originalCaseDecisionDate] NVARCHAR(max),
    [targetDate] NVARCHAR(max),
    [siteGridReferenceEasting] NVARCHAR(max),
    [siteGridReferenceNorthing] NVARCHAR(max),
    [hasLandownersPermission] BIT,
    [isSiteInAreaOfSpecialControlAdverts] BIT,
    [wasApplicationRefusedDueToHighwayOrTraffic] BIT,
    [didAppellantSubmitCompletePhotosAndPlans] BIT,
    [advertDetails] NVARCHAR(max),
    [lpaProcedurePreferenceDetails] NVARCHAR(max),
    [designatedSitesNames] NVARCHAR(max),
    [lpaProcedurePreference] NVARCHAR(max),
    [lpaProcedurePreferenceDuration] DECIMAL(32,16),
    [padsSapId] NVARCHAR(max),
    CONSTRAINT [appeal_has_pkey] PRIMARY KEY CLUSTERED ([caseId])
);

-- CreateTable
CREATE TABLE [dbo].[appeal_representation] (
    [representationId] NVARCHAR(1000) NOT NULL,
    [caseId] INT,
    [caseReference] NVARCHAR(max),
    [representationStatus] NVARCHAR(max),
    [originalRepresentation] NVARCHAR(max),
    [redacted] BIT,
    [redactedRepresentation] NVARCHAR(max),
    [redactedBy] NVARCHAR(max),
    [invalidOrIncompleteDetails] NVARCHAR(max),
    [otherInvalidOrIncompleteDetails] NVARCHAR(max),
    [source] NVARCHAR(max),
    [serviceUserId] NVARCHAR(max),
    [representationType] NVARCHAR(max),
    [dateReceived] NVARCHAR(max),
    [documentIds] NVARCHAR(max),
    CONSTRAINT [appeal_representation_pkey] PRIMARY KEY CLUSTERED ([representationId])
);

-- CreateTable
CREATE TABLE [dbo].[appeal_s78] (
    [caseReference] NVARCHAR(max),
    [caseId] INT NOT NULL,
    [submissionId] NVARCHAR(max),
    [caseStatus] NVARCHAR(max),
    [caseType] NVARCHAR(max),
    [caseProcedure] NVARCHAR(max),
    [lpaCode] NVARCHAR(max),
    [caseOfficerId] NVARCHAR(max),
    [inspectorId] NVARCHAR(max),
    [allocationLevel] NVARCHAR(max),
    [allocationBand] DECIMAL(32,16),
    [caseSpecialisms] NVARCHAR(max),
    [caseSubmittedDate] NVARCHAR(max),
    [caseCreatedDate] NVARCHAR(max),
    [caseUpdatedDate] NVARCHAR(max),
    [caseValidDate] NVARCHAR(max),
    [caseValidationDate] NVARCHAR(max),
    [caseValidationOutcome] NVARCHAR(max),
    [caseValidationInvalidDetails] NVARCHAR(max),
    [caseValidationIncompleteDetails] NVARCHAR(max),
    [caseExtensionDate] NVARCHAR(max),
    [caseStartedDate] NVARCHAR(max),
    [casePublishedDate] NVARCHAR(max),
    [linkedCaseStatus] NVARCHAR(max),
    [leadCaseReference] NVARCHAR(max),
    [lpaQuestionnaireDueDate] NVARCHAR(max),
    [lpaQuestionnaireSubmittedDate] NVARCHAR(max),
    [lpaQuestionnaireCreatedDate] NVARCHAR(max),
    [lpaQuestionnairePublishedDate] NVARCHAR(max),
    [lpaQuestionnaireValidationOutcome] NVARCHAR(max),
    [lpaQuestionnaireValidationOutcomeDate] NVARCHAR(max),
    [lpaQuestionnaireValidationDetails] NVARCHAR(max),
    [lpaStatement] NVARCHAR(max),
    [caseWithdrawnDate] NVARCHAR(max),
    [caseTransferredDate] NVARCHAR(max),
    [transferredCaseClosedDate] NVARCHAR(max),
    [caseDecisionOutcomeDate] NVARCHAR(max),
    [caseDecisionPublishedDate] NVARCHAR(max),
    [caseDecisionOutcome] NVARCHAR(max),
    [caseCompletedDate] NVARCHAR(max),
    [enforcementNotice] BIT,
    [applicationReference] NVARCHAR(max),
    [applicationDate] NVARCHAR(max),
    [applicationDecision] NVARCHAR(max),
    [applicationDecisionDate] NVARCHAR(max),
    [caseSubmissionDueDate] NVARCHAR(max),
    [siteAddressLine1] NVARCHAR(max),
    [siteAddressLine2] NVARCHAR(max),
    [siteAddressTown] NVARCHAR(max),
    [siteAddressCounty] NVARCHAR(max),
    [siteAddressPostcode] NVARCHAR(max),
    [siteAccessDetails] NVARCHAR(max),
    [siteSafetyDetails] NVARCHAR(max),
    [siteAreaSquareMetres] DECIMAL(32,16),
    [floorSpaceSquareMetres] DECIMAL(32,16),
    [isCorrectAppealType] BIT,
    [isGreenBelt] BIT,
    [inConservationArea] BIT,
    [ownsAllLand] BIT,
    [ownsSomeLand] BIT,
    [knowsOtherOwners] NVARCHAR(max),
    [knowsAllOwners] NVARCHAR(max),
    [advertisedAppeal] BIT,
    [notificationMethod] NVARCHAR(max),
    [ownersInformed] BIT,
    [originalDevelopmentDescription] NVARCHAR(max),
    [changedDevelopmentDescription] BIT,
    [newConditionDetails] NVARCHAR(max),
    [nearbyCaseReferences] NVARCHAR(max),
    [neighbouringSiteAddresses] NVARCHAR(max),
    [affectedListedBuildingNumbers] NVARCHAR(max),
    [changedListedBuildingNumbers] NVARCHAR(max),
    [appellantCostsAppliedFor] BIT,
    [lpaCostsAppliedFor] BIT,
    [agriculturalHolding] BIT,
    [tenantAgriculturalHolding] BIT,
    [otherTenantsAgriculturalHolding] BIT,
    [informedTenantsAgriculturalHolding] BIT,
    [appellantProcedurePreference] NVARCHAR(max),
    [appellantProcedurePreferenceDetails] NVARCHAR(max),
    [appellantProcedurePreferenceDuration] DECIMAL(32,16),
    [appellantProcedurePreferenceWitnessCount] DECIMAL(32,16),
    [statusPlanningObligation] NVARCHAR(max),
    [affectsScheduledMonument] BIT,
    [hasProtectedSpecies] BIT,
    [isAonbNationalLandscape] BIT,
    [designatedSitesNames] NVARCHAR(max),
    [isGypsyOrTravellerSite] BIT,
    [isPublicRightOfWay] BIT,
    [eiaEnvironmentalImpactSchedule] NVARCHAR(max),
    [eiaDevelopmentDescription] NVARCHAR(max),
    [eiaSensitiveAreaDetails] NVARCHAR(max),
    [eiaColumnTwoThreshold] BIT,
    [eiaScreeningOpinion] BIT,
    [eiaRequiresEnvironmentalStatement] BIT,
    [eiaCompletedEnvironmentalStatement] BIT,
    [hasStatutoryConsultees] BIT,
    [consultedBodiesDetails] NVARCHAR(max),
    [hasInfrastructureLevy] BIT,
    [isInfrastructureLevyFormallyAdopted] BIT,
    [infrastructureLevyAdoptedDate] NVARCHAR(max),
    [infrastructureLevyExpectedDate] NVARCHAR(max),
    [lpaProcedurePreference] NVARCHAR(max),
    [lpaProcedurePreferenceDetails] NVARCHAR(max),
    [lpaProcedurePreferenceDuration] DECIMAL(32,16),
    [caseworkReason] NVARCHAR(max),
    [developmentType] NVARCHAR(max),
    [importantInformation] NVARCHAR(max),
    [jurisdiction] NVARCHAR(max),
    [redeterminedIndicator] NVARCHAR(max),
    [dateCostsReportDespatched] NVARCHAR(max),
    [dateNotRecoveredOrDerecovered] NVARCHAR(max),
    [dateRecovered] NVARCHAR(max),
    [originalCaseDecisionDate] NVARCHAR(max),
    [targetDate] NVARCHAR(max),
    [appellantCommentsSubmittedDate] NVARCHAR(max),
    [appellantStatementSubmittedDate] NVARCHAR(max),
    [appellantProofsSubmittedDate] NVARCHAR(max),
    [finalCommentsDueDate] NVARCHAR(max),
    [interestedPartyRepsDueDate] NVARCHAR(max),
    [lpaCommentsSubmittedDate] NVARCHAR(max),
    [lpaProofsSubmittedDate] NVARCHAR(max),
    [lpaStatementSubmittedDate] NVARCHAR(max),
    [proofsOfEvidenceDueDate] NVARCHAR(max),
    [siteNoticesSentDate] NVARCHAR(max),
    [statementDueDate] NVARCHAR(max),
    [reasonForNeighbourVisits] NVARCHAR(max),
    [numberOfResidencesNetChange] DECIMAL(32,16),
    [siteGridReferenceEasting] NVARCHAR(max),
    [siteGridReferenceNorthing] NVARCHAR(max),
    [siteViewableFromRoad] BIT,
    [siteWithinSSSI] BIT,
    [typeOfPlanningApplication] NVARCHAR(max),
    [preserveGrantLoan] BIT,
    [consultHistoricEngland] BIT,
    [planningObligationDueDate] NVARCHAR(max),
    [hasLandownersPermission] BIT,
    [wasApplicationRefusedDueToHighwayOrTraffic] BIT,
    [didAppellantSubmitCompletePhotosAndPlans] BIT,
    [isSiteInAreaOfSpecialControlAdverts] BIT,
    [advertDetails] NVARCHAR(max),
    [padsSapId] NVARCHAR(max),
    [statementOfCommonGroundDueDate] NVARCHAR(max),
    [issueDateOfEnforcementNotice] NVARCHAR(max),
    [effectiveDateOfEnforcementNotice] NVARCHAR(max),
    [enforcementAppealGroundsDetails] NVARCHAR(max),
    [ownerOccupancyStatus] NVARCHAR(max),
    [occupancyConditionsMet] BIT,
    [applicationMadeAndFeePaid] BIT,
    [noticeRelatesToBuildingEngineeringMiningOther] BIT,
    [changeOfUseRefuseOrWaste] BIT,
    [changeOfUseMineralExtraction] BIT,
    [changeOfUseMineralStorage] BIT,
    [relatesToErectionOfBuildingOrBuildings] BIT,
    [relatesToBuildingWithAgriculturalPurpose] BIT,
    [relatesToBuildingSingleDwellingHouse] BIT,
    [previousPlanningPermissionGranted] BIT,
    [didAppellantAppealLpaDecision] BIT,
    [dateLpaDecisionDue] NVARCHAR(max),
    [dateLpaDecisionReceived] NVARCHAR(max),
    [areaOfAllegedBreachInSquareMetres] DECIMAL(32,16),
    [doesAllegedBreachCreateFloorSpace] BIT,
    [floorSpaceCreatedByBreachInSquareMetres] DECIMAL(32,16),
    [applicationPartOrWholeDevelopment] NVARCHAR(max),
    [hasPcnBeenServed] BIT,
    [isSiteWithin67MOfTrunkRd] BIT,
    [affectedTrunkRoadName] NVARCHAR(max),
    [isSiteOnCrownLand] BIT,
    [stopNoticeExists] BIT,
    [isSiteWithin400MOfMineralInterest] BIT,
    [isSiteWithin250MOfLandfill] BIT,
    [hasDevelopmentInvolvedWasteImportation] BIT,
    [isSiteSubjectToArticle4Direction] BIT,
    [article4AffectedDevelopmentRights] NVARCHAR(max),
    [pcnRestrictedDevelopmentRights] BIT,
    CONSTRAINT [appeal_s78_pkey] PRIMARY KEY CLUSTERED ([caseId])
);

-- CreateTable
CREATE TABLE [dbo].[appeal_service_user] (
    [id] NVARCHAR(1000) NOT NULL,
    [salutation] NVARCHAR(max),
    [firstName] NVARCHAR(max),
    [lastName] NVARCHAR(max),
    [addressLine1] NVARCHAR(max),
    [addressLine2] NVARCHAR(max),
    [addressTown] NVARCHAR(max),
    [addressCounty] NVARCHAR(max),
    [postcode] NVARCHAR(max),
    [addressCountry] NVARCHAR(max),
    [organisation] NVARCHAR(max),
    [organisationType] NVARCHAR(max),
    [role] NVARCHAR(max),
    [telephoneNumber] NVARCHAR(max),
    [otherPhoneNumber] NVARCHAR(max),
    [faxNumber] NVARCHAR(max),
    [emailAddress] NVARCHAR(max),
    [webAddress] NVARCHAR(max),
    [serviceUserType] NVARCHAR(max),
    [caseReference] NVARCHAR(max),
    [sourceSuid] NVARCHAR(max),
    [sourceSystem] NVARCHAR(max),
    CONSTRAINT [appeal_service_user_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
